### ISSUE TITLE
Integrate Sofia build system into R3BRoot

### ISSUE THREAD

**Issue by kresan** [R3BRootGroup/sofia#2]
The idea is to have only one global CMakeLists.txt with configuration (in R3BRoot), which includes sofia sub-directory (if found) and builds it together with all other subdirectories into multiple shared libraries. Will simplify a lot: one build directory, one call to cmake and make.

@hapol is it the way you would like to have it?

If you agree, I will start implementing it on both sides.

**Comment by hapol** [comment]
Yes, I think it would simplify it, thank you.
If you can implement the structure with the present classes, I'll take care of preserving for the new classes we are adding.

**Comment by kresan** [comment]
issues is solved in #3
