### ISSUE TITLE
Moving twim and mwpc folders into R3BRoot repository

### ISSUE THREAD

**Issue by jose-luis-rs** [R3BRootGroup/sofia#266]
I need to move these detectors into the R3BRoot repository to facilitate the implementation of correlations with other R3B detectors. So the plan is very basic:
- MWPCs: Move the folder and change the names to R3BMwpc...
- Twim: Move the folder and change the names to R3BTwim.., additionally I will change the 0-base arrangement to 1-base for sections and anodes.
I will do all the needed changes to ensure the code compilation. People having private analysis macros will need to update the name of these classes.
#
Best regards

**Comment by ryotani** [comment]
I think moving MWPC and Twim to the main repository is a good idea. I have two points which I would like to make clear.
1. Do you plan to create a dedicated directory for Twim, or create another one independent of R3BMusic? I think there's a similarity between R3BMusic and Twim for the concept of the detector. But can be independent. Either would work for everyone I suppose.
2. Does the movement would include the change in the names of the parameters and their containers? If we can make a table for listing the corresponding names for old and new ones, it would be good?

**Comment by jose-luis-rs** [comment]
1) Currently we have three ionization chambers in independent folders, this will not change after the moving.

2) The modification of names only affects the classes, so the name of the parameters and their containers will not change. This means that you do not need to change anything in your parameter input files.

If you obtain any problem after the moving, please, tell me as soon as possible to look for a solution.
